### PR TITLE
Release v0.3.1

### PR DESCRIPTION
**Pull request by mrattle**
Patch release that incorporates changes made to the value type of `set` and `add` methods (prev: `AsRef`, now: `AsMemcachedValue`) and fixes an issue with DNS lookup.

This release covers changes from the following PR(s):
- https://github.com/Shopify/async-memcached/pull/28
- https://github.com/Shopify/async-memcached/pull/31

`cargo release minor -v` dryrun diff:
```
Upgrading async-memcached from 0.3.0 to 0.3.1
[2024-09-09T17:37:48Z DEBUG cargo_release::ops::cargo] change:
    --- /Users/mark/src/github.com/Shopify/async-memcached/Cargo.toml   original
    +++ /Users/mark/src/github.com/Shopify/async-memcached/Cargo.toml   updated
    @@ -1,6 +1,6 @@
     [package]
     name = "async-memcached"
    -version = "0.3.0"
    +version = "0.3.1"
     authors = ["Toby Lawrence <toby@nuclearfurnace.com>"]
     edition = "2018"
     readme = "README.md"
    
[2024-09-09T17:37:48Z DEBUG cargo_release::steps::release] updating lock file
[2024-09-09T17:37:48Z DEBUG cargo_release::ops::replace] processing replacements for file /Users/mark/src/github.com/Shopify/async-memcached/CHANGELOG.md
   Replacing in CHANGELOG.md
--- CHANGELOG.md        original
+++ CHANGELOG.md        replaced
@@ -1,7 +1,7 @@
 # Changelog
 
 All notable changes to this project will be documented in this file.
-Keep a running log of your changes with each PR under the `[Unreleased] - ReleaseDate` header.
+Keep a running log of your changes with each PR under the `[0.3.1] - 2024-09-09` header.
```

### CODE REVIEW

**Review by adampetro — COMMENTED** [review]
I think we need to update the version number in `Cargo.toml`

**Comment by mrattle** [comment]
> I think we need to update the version number in `Cargo.toml`

That gets pushed to this PR automatically as part of the `--execute` process with `cargo-release`.

**Comment by mrattle** [comment]
> Just to confirm, the bug fix was this [PR](https://github.com/Shopify/async-memcached/pull/31)?

Correct.

Added the dryrun diff to the PR description, thought I had dropped that in there already...

**Comment by adampetro** [comment]
> That gets pushed to this PR automatically as part of the `--execute` process with `cargo-release`.

Interesting. My preference is to release from `main` after merging the version bump, as it ensures we deploy up to date changes, but if we prefer this approach, can we document it somewhere?

**Review by makrisoft — APPROVED** [review]

**Pull request merged**
